services:
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - '../../../codecake-yt/postgres:/var/lib/postgresql/data'
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
